/**
 * Deck loading.
 *
 * Decks come from two kinds of place:
 *
 *   built-in  the decks shipped in the image, under decks/
 *   extra     zero or more directories mounted at runtime — a bind mount
 *             locally, a ConfigMap or PVC on Kubernetes
 *
 * Extra directories hold files nobody reviewed, so they are treated as
 * untrusted input: every deck is validated, card ids are namespaced by deck
 * id, and a file that fails is skipped with a logged reason rather than
 * bringing the server down. A typo in someone's custom deck should not stop
 * the game starting.
 */
import { existsSync, readdirSync, readFileSync, statSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { Deck } from '@cac/shared/deck';
import { validateDeckJson } from '@cac/shared/deck-validate';

const HERE = dirname(fileURLToPath(import.meta.url));
export const BUILTIN_DECK_DIR = join(HERE, '..', '..', '..', 'decks');

/** Refuse absurd files before parsing them. 4 MB is far past any real deck. */
const MAX_DECK_FILE_BYTES = 4 * 1024 * 1024;

export interface DeckLoadResult {
  decks: Deck[];
  /** Problems worth surfacing in logs; never fatal. */
  problems: string[];
}

export interface LoadOptions {
  builtinDir?: string;
  /** Extra directories, searched in order after the built-ins. */
  extraDirs?: readonly string[];
}

/**
 * Directories to search for custom decks, from CAC_DECK_DIRS (colon-separated,
 * like PATH). Missing directories are fine — a ConfigMap that has not been
 * created yet should not be an error.
 */
export function extraDeckDirsFromEnv(env: NodeJS.ProcessEnv = process.env): string[] {
  return (env['CAC_DECK_DIRS'] ?? '')
    .split(':')
    .map((d) => d.trim())
    .filter((d) => d.length > 0);
}

function readDeckFiles(dir: string, problems: string[]): { file: string; json: unknown }[] {
  if (!existsSync(dir)) return [];
  let entries: string[];
  try {
    entries = readdirSync(dir);
  } catch (err) {
    problems.push(`${dir}: cannot read directory (${(err as Error).message})`);
    return [];
  }

  const out: { file: string; json: unknown }[] = [];
  for (const entry of entries.sort()) {
    // ConfigMap mounts are full of ..data and ..2024_01_01 symlink shims.
    if (entry.startsWith('.') || !entry.endsWith('.json')) continue;
    const path = join(dir, entry);
    try {
      if (!statSync(path).isFile()) continue;
      if (statSync(path).size > MAX_DECK_FILE_BYTES) {
        problems.push(`${path}: larger than ${MAX_DECK_FILE_BYTES} bytes, skipped`);
        continue;
      }
      out.push({ file: path, json: JSON.parse(readFileSync(path, 'utf8')) });
    } catch (err) {
      problems.push(`${path}: ${(err as Error).message}`);
    }
  }
  return out;
}

export function loadDecksDetailed(options: LoadOptions = {}): DeckLoadResult {
  const builtinDir = options.builtinDir ?? BUILTIN_DECK_DIR;
  const extraDirs = options.extraDirs ?? extraDeckDirsFromEnv();
  const problems: string[] = [];
  const decks: Deck[] = [];
  const byId = new Map<string, string>();

  // Built-ins are generated by scripts/import-deck.ts and already validated at
  // import time, so they are taken as-is; re-validating would only risk
  // rejecting a shipped deck at boot over a rule change.
  for (const { file, json } of readDeckFiles(builtinDir, problems)) {
    const deck = json as Deck;
    if (!deck?.id || !Array.isArray(deck.prompts) || !Array.isArray(deck.responses)) {
      problems.push(`${file}: malformed built-in deck, skipped`);
      continue;
    }
    decks.push(deck);
    byId.set(deck.id, file);
  }

  if (decks.length === 0) {
    throw new Error(`no built-in decks found in ${builtinDir}`);
  }

  for (const dir of extraDirs) {
    for (const { file, json } of readDeckFiles(dir, problems)) {
      const result = validateDeckJson(json);
      if (!result.ok || !result.deck) {
        const detail = result.errors.map((e) => `${e.field}${e.line ? ` line ${e.line}` : ''}: ${e.message}`);
        problems.push(`${file}: invalid deck, skipped — ${detail.join('; ')}`);
        continue;
      }
      // A custom deck must not shadow a built-in one: the lobby keys decks by
      // id, so two decks sharing one would be indistinguishable there.
      const clash = byId.get(result.deck.id);
      if (clash) {
        problems.push(`${file}: deck id "${result.deck.id}" already used by ${clash}, skipped`);
        continue;
      }
      for (const warning of result.warnings) {
        problems.push(`${file}: ${warning.field}${warning.line ? ` line ${warning.line}` : ''}: ${warning.message}`);
      }
      decks.push(result.deck);
      byId.set(result.deck.id, file);
    }
  }

  decks.sort((a, b) => a.id.localeCompare(b.id));
  return { decks, problems };
}

export function loadDecks(options: LoadOptions = {}): Deck[] {
  return loadDecksDetailed(options).decks;
}

export function defaultDeckIds(decks: readonly Deck[]): string[] {
  const enabled = decks.filter((d) => d.defaultEnabled).map((d) => d.id);
  return enabled.length > 0 ? enabled : [decks[0]!.id];
}
